//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Balakin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.SqlClient;
    using System.Linq;
    using System.Windows;

    public partial class DataBaseEntities : DbContext
    {
        public DataBaseEntities()
            : base("name=DataBaseEntities")
        {
        }


        public virtual DbSet<admins> admins { get; set; }
        public virtual DbSet<users> users { get; set; }


        public bool InsertUser(string login, string password)
        {
            bool result = false;

            using (SqlConnection connection = new SqlConnection("Server=DESKTOP-0JL8ELS\\BD;Database=TEST;Trusted_Connection=True;MultipleActiveResultSets=True;"))
            {
                string query = "INSERT INTO users (login, password) VALUES (@login, @password)";

                using (SqlCommand command = new SqlCommand(query, connection))
                {
                    command.Parameters.AddWithValue("@login", login);
                    command.Parameters.AddWithValue("@password", password);

                    connection.Open();
                    int rowsAffected = command.ExecuteNonQuery();

                    if (rowsAffected > 0)
                    {
                        result = true;
                    }
                    else
                    {
                        MessageBox.Show("Error: User not inserted");
                    }
                }
            }

            return result;
        }
    }
}

