//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Balakin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    using System.Windows;

    public partial class DataBaseEntities : DbContext
    {
        public DataBaseEntities()
            : base("name=DataBaseEntities")
        {
        }


        public virtual DbSet<admins> admins { get; set; }
        public virtual DbSet<users> users { get; set; }


        public bool InsertUser(string login, string password)
        {
            bool result = false;

            using (var context = new DataBaseEntities())
            {
                using (var dataBase = new DataBaseEntities())
                    {
                    try
                    {
                        // Создаем новый объект user
                        var user = new users { login = login, password = password };

                        // Добавляем его в таблицу users
                        dataBase.users.Add(user);

                        // Сохраняем изменения в базе данных
                        dataBase.SaveChanges();

                        result = true;
                            
                        }
                        catch (Exception ex)
                        {
                        // Если произошла ошибка при добавлении записи в базу, выводим ее в консоль
                        Console.WriteLine("Error: " + ex.Message);
                        }
                        return result;
                    }
                }
            }
        }
    }

